dbt_project:
  outputs:
    dev:
      account: FHYBDIQ-GNB78294
      database: DEMO_DB_DBT
      password: $ELIMADBTCOURSE1_KEY
      role: ACCOUNTADMIN
      schema: RAW
      threads: 1
      type: snowflake
      user: elimadbtcourse1
      warehouse: COMPUTE_WH
  target: dev
