version: 2

sources:
  - name: SNOWFLAKE_SOURCE
    description: "Source Snowflake"
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
        - name: orders
          description: "Tabela de Pedidos"
          freshness:
            warn_after:
              count: 100
              period: day
            error_after:
              count: 200
              period: day
          loaded_at_field: O_ORDERDATE::timestamp
        - name: nation
          description: "Tabela de PaÍses"
        - name: region
          description: "Tabela de Regiões"
          tests:
            - accepted_values:
                values: [0,1,2,3,4]